name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-tests:
    name: Build and tests
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'analytics-providers-template'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: 📦 Initialize
        uses: Marfeel/github-actions/common/actions/initialize@master
        with:
          gh-token: ${{ secrets.GH_PACKAGE_REGISTRY_TOKEN }}

      - name: 🛠 Build
        uses: Marfeel/github-actions/providers/analytics/build@master

      - name: ✅ Lint & Tests
        uses: Marfeel/github-actions/providers/analytics/test@master

      - name: 🚀 Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: Marfeel/github-actions/providers/analytics/publish@master
        with:
          gh-token: ${{ secrets.GH_PACKAGE_REGISTRY_TOKEN }}
          nexus-token: ${{ secrets.NPM_NEXUS_AUTH }}
          aws-key: ${{ secrets.AWS_KEY }}
          aws-secret: ${{ secrets.AWS_SECRET }}
          build-number: ${{ github.run_id }}
